### ISSUE TITLE
melonDS/src does not appear to contain CMakeLists.txt.

### ISSUE THREAD

**Issue by peterlouvel** [Rinnegatamante/melonDS-Vita#4]
I'm in the build directory
I run **cmake ..**
melonDS/src/build# **cmake ..**

CMake Error: The source directory "melonDS/src" does not appear to contain CMakeLists.txt.

I am in Ubuntu  **Windows Subsystem for Linux**  I added the following packages

sudo apt install g++ gdb make rsync zip
sudo apt-get install cmake gcc clang gdb build-essential

![cmake error](https://user-images.githubusercontent.com/240880/71720600-0269f480-2e6e-11ea-84ad-7477f205b993.png)

**Comment by Rinnegatamante** [comment]
![immagine](https://user-images.githubusercontent.com/9152710/71724296-24dd1d00-2e30-11ea-9709-117459f33026.png)

**Comment by peterlouvel** [comment]
how do I use the Makefile?   I just followed your info in the readme

**Comment by Rinnegatamante** [comment]
The info on the readme are for the PC version.
You're not supposed to compile this and i'm not going to give any more support into compiling this since completely useless.
